remote_theme: jekyll/minima

minima:
  skin: dark
  date_format: "%b %-d, %Y"

plugins:
  - jekyll-remote-theme

title: Commodity Linear Regression
description: Final project for EECS 398: Practical Data Science
github_repo: https://github.com/trullin-umich/commodity_linear_regression